name: Typecheck

on:
  pull_request:
    branches: 
    - main
    
jobs:
  Typecheck:
    runs-on: ubuntu-latest
    name: Check type errores
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run typecheck

 